version: "0.1"
services:
  redis:
    image: 'redis:4-alpine'
    ports:
      - '6379:6379'

  rabbit:
    hostname: rabbit
    image: "rabbitmq:3-management"
    environment:
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=mypass
    ports:
      - "15672:15672"
      - "5672:5672"

  hard_worker:
    build: './hard_worker'
    user: nobody
    depends_on:
      - rabbit
      - redis
      - flask_app

  lazy_worker:
    build: './lazy_worker'
    user: nobody
    depends_on:
      - rabbit
      - redis
      - flask_app

  flask_app:
    build: './flask_app'
    ports:
      - "5001:5001"
    depends_on:
      - rabbit
      - redis